"""empty message

Revision ID: 14ab006ceda7
Revises: 20d07d9cb9d0
Create Date: 2017-04-08 17:48:16.090000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ab006ceda7'
down_revision = '20d07d9cb9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('old_login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'old_login_time')
    # ### end Alembic commands ###
