"""empty message

Revision ID: 2314ca625df1
Revises: 5176002c3efe
Create Date: 2017-04-02 10:34:16.800000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2314ca625df1'
down_revision = '5176002c3efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('origin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['origin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'origin_id')
    # ### end Alembic commands ###
