"""empty message

Revision ID: 5b7f78e72ec8
Revises: ae9fd2afe4b9
Create Date: 2017-04-01 11:58:03.695000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7f78e72ec8'
down_revision = 'ae9fd2afe4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlightpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'post', sa.Column('highlight_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'highlightpost', ['highlight_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column(u'post', 'highlight_id')
    op.drop_table('highlightpost')
    # ### end Alembic commands ###
