"""empty message

Revision ID: 9763ac9432b2
Revises: 5b7f78e72ec8
Create Date: 2017-04-01 17:09:03.813000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9763ac9432b2'
down_revision = '5b7f78e72ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlightpost', sa.Column('name', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('highlightpost', 'name')
    # ### end Alembic commands ###
